name: Build a Hava release

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  build:

    name: Build and test
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.15.2' # [Required] Define the Elixir version
        otp-version: '26.0'      # [Required] Define the Erlang/OTP version
        
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
        
    - name: Install dependencies
      run: mix deps.get
        
    - name: Run tests
      run: mix test
        
    - name: Create release artifact
      run: MIX_ENV=prod mix release --overwrite
        
    - name: Release
      uses: softprops/action-gh-release@v1
      # if: startsWith(github.ref, 'refs/tags/')
      with:
        files: _build/prod/hava-0.1.0.tar.gz
        name: Hava V0.1.0
        body: Initial release to test and evaluate
    # - name: Release
    #   uses: fnkr/github-action-ghr@v1
    #   # if: startsWith(github.ref, 'refs/tags/')
    #   env:
    #     GHR_PATH: _build/prod/hava-0.1.0.tar.gz
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - uses: xresloader/upload-to-github-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     file: _build/prod/hava-0.1.0.tar.gz
    #     tags: false
    #     draft: false
    #     overwrite: true
    #     verbose: true
    #     default_release_name: hava-0.1.0-rc
